### ISSUE TITLE
Anova Precision Cooker Pro reporting 'Retrying setup: 'water-temp-too-high'

### ISSUE THREAD

**Issue by roberthamilton-pm** [Lash-L/anova-wifi-hacs#28]
## Version of the custom_component

2.1.0

## Configuration

```yaml
Add your logs here.
```

## Describe the bug

When I installed the component and set it up, I get an error saying 'Retrying setup: 'water-temp-too-high''. Restarting HA doesn't fix the issue.

I've attached the output from https://anovaculinary.io/devices/<deviceID>/states/?limit=1 below in the hope that it sheds light on the issue.

## Debug log

```text

Logger: custom_components.anova_sous_vide.coordinator
Source: custom_components/anova_sous_vide/coordinator.py:53
Integration: Anova Sous Vide
First occurred: 5:15:01 PM (18 occurrences)
Last logged: 5:34:41 PM

Unexpected error fetching Anova Precision Cooker data: 'water-temp-too-high'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/anova_sous_vide/coordinator.py", line 53, in _async_update_data
    return await self.anova_device.update()
  File "/usr/local/lib/python3.10/site-packages/anova_wifi/precission_cooker.py", line 138, in update
    AnovaPrecisionCookerBinarySensor.WATER_TEMP_TOO_HIGH: anova_status[
KeyError: 'water-temp-too-high'

[
	{
		"body": {
			"audio-control": {
				"file-name": "",
				"volume": 24
			},
			"boot-id": "43435004281963",
			"cap-touch": {
				"minus-button": 0,
				"play-button": 0,
				"plus-button": 0,
				"target-temperature-button": 0,
				"timer-button": 0,
				"water-temperature-button": 0
			},
			"heater-control": {
				"duty-cycle": 0
			},
			"job": {
				"cook-time-seconds": 0,
				"id": "133363029513723",
				"mode": "IDLE",
				"ota-url": "",
				"target-temperature": 60,
				"temperature-unit": "F"
			},
			"job-status": {
				"cook-time-remaining": 0,
				"job-start-systick": 14428,
				"provisioning-pairing-code": 0,
				"state": "",
				"state-change-systick": 14428
			},
			"motor-control": {
				"duty-cycle": 0
			},
			"motor-info": {
				"rpm": 0
			},
			"network-info": {
				"bssid": "HIDDEN",
				"connection-status": "connected-station",
				"is-provisioning": false,
				"mac-address": "68474906DF3D",
				"mode": "station",
				"security-type": "WPA2",
				"ssid": "HIDDEN"
			},
			"pin-info": {
				"device-safe": 1,
				"motor-stuck": 1,
				"water-leak": 0,
				"water-level-critical": 0,
				"water-level-low": 0
			},
			"system-info-2640": {
				"firmware-version": "3.3.32",
				"firmware-version-sha": "3.3.32",
				"largest-free-heap-size": 1208,
				"mcu-temperature": 36,
				"systick": 1018692,
				"total-free-heap-size": 1208,
				"total-heap-size": 16384
			},
			"system-info-3220": {
				"firmware-version": "3.3.35",
				"firmware-version-sha": "3.3.35",
				"fwUpgradeStatus": 0,
				"has-real-cert-catalog": true,
				"largest-free-heap-size": 19808,
				"systick": 1034081,
				"total-free-heap-size": 21112,
				"total-heap-size": 65536
			},
			"temperature-info": {
				"heater-temperature": 53.78,
				"triac-temperature": 47,
				"water-temperature": 53.94
			}
		},
		"header": {
			"created-at": "2023-04-04T21:20:29.126657Z",
			"e-tag": "5fd0107f3d15a3c854011fd2f0131e97521c8a093affda36776c7cced5072894",
			"entity-id": "86023899987927"
		}
	}
]

```

**Comment by Lash-L** [comment]
Oh wow - your status is very different from mine - what model sous vide do you have?

**Comment by roberthamilton-pm** [comment]
It's the Precision Cooker Pro — it reports a lot of status!

**Comment by Lash-L** [comment]
@roberthamilton-pm Redownload in hacs using "main" as the version and let me know if that works

Can you also send me the exact model # on the back of your device?

**Comment by roberthamilton-pm** [comment]
Yes - that is working now, thank you so much.

AN600-10 is the model number for the Pro version.
